# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20180817_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link_fb',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
    ]
