# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10, verbose_name='Название книги')),
                ('release_data', models.DateField(verbose_name='Дата релиза')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author', verbose_name='Автор')),
            ],
        ),
    ]
