# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180812_2038'),
        ('post', '0002_auto_20180808_2122'),
    ]

    operations = [
    ]
