# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180806_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='client',
            field=models.CharField(blank=True, max_length=20, verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='partnership',
            field=models.CharField(blank=True, max_length=20, verbose_name='Парнеры'),
        ),
    ]
